# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  # Change to your release branch

stages:
  - stage: InstallDependencies
    displayName: "Install Node and Yarn Dependencies"
    jobs:
      - job: Install
        pool:
          vmImage: 'macos-latest'  # macOS can build both Android and iOS
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install -g yarn
              yarn install
            displayName: 'Install yarn dependencies'

  - stage: BuildAndroid
    displayName: "Build Android App"
    dependsOn: InstallDependencies
    jobs:
      - job: AndroidBuild
        pool:
          vmImage: 'macos-latest'
        steps:
          - task: Gradle@2
            inputs:
              workingDirectory: 'android'
              gradleWrapperFile: 'android/gradlew'
              gradleOptions: '-Xmx3072m'
              tasks: 'assembleRelease'
            displayName: 'Assemble Android APK'

          - task: CopyFiles@2
            inputs:
              contents: '**/*.apk'
              targetFolder: '$(Build.ArtifactStagingDirectory)/apk'
            displayName: 'Copy APKs to staging'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/apk'
              artifactName: 'Android_APK'
            displayName: 'Publish APK artifact'

  # - stage: BuildiOS
  #   displayName: "Build iOS App"
  #   dependsOn: InstallDependencies
  #   jobs:
  #     - job: iOSBuild
  #       pool:
  #         name: 'YourMacAgentPool'  # Replace with your self-hosted macOS agent pool
  #       steps:
  #         - script: |
  #             cd ios
  #             pod install
  #           displayName: 'Install CocoaPods'

  #         - task: Xcode@5
  #           inputs:
  #             actions: 'build'
  #             scheme: 'YourAppScheme'  # Replace with your Xcode scheme
  #             sdk: 'iphoneos'
  #             configuration: 'Release'
  #             xcWorkspacePath: 'ios/YourApp.xcworkspace'
  #             signingOption: 'manual'
  #             signingIdentity: '$(SIGNING_IDENTITY)'
  #             provisioningProfileUuid: '$(PROVISIONING_PROFILE_UUID)'
  #           displayName: 'Build iOS App'

  #         - task: PublishBuildArtifacts@1
  #           inputs:
  #             pathToPublish: 'ios/build'
  #             artifactName: 'iOS_App'
  #           displayName: 'Publish iOS artifact'
